# Header-菜单
menu:
  主页: /
  标签: /tags
  分类: /categories
  相册: /photos
  随笔: /notes
  归档: /archives

menu_icons:
  enable: true
  # Icon Mapping.
  home: home
  about: user
  categories: th
  tags: tags
  archives: archive

# subNav-子导航
subNav:
  github: https://github.com/YaoJusheng
  gitee: https://gitee.com/YaoJusheng  # 码云
  # jianshu: "#" #简书
  # cnblog: "#"
  #blog: "#"
  csdn: "https://blog.csdn.net/weixin_41599858"
  # rss: /atom.xml
  # zhihu: "https://www.zhihu.com/people/qing-kuang-shu-sheng-78-59"
  #qq: "#"
  #weixin: "#"
  #weibo: "#"
  #douban: "#"
  #segmentfault: "#"
  # bilibili: "https://www.bilibili.com/"
  #acfun: "#"
  mail: "mailto:jusheng_yao@outlook.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

# 悬停预览图片效果
hover_effect:
  ## `global` 0: Set separately, 1: Enable global 2: Close global
  ## `global` 0: 分开设置, 1: 全局启用, 2: 全局关闭
  global: 2
  # SubNav-导航
  subNav: true

# RSS订阅(关于如何配置启用:https://www.jianshu.com/p/2aaac7a19736)
rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 / 设为 /blog/。
# 新版本已弃用，请在博客根目录文件进行配置
# root: /blog/

# Content
# 文章太长，截断按钮文字(在需要截断的行增加此标记：<!--more-->)
# excerpt_link: more
archive_yearly: true #按年存档
fancybox: true

# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'

# 文章结束语
end_message:
  enable: true
  default: 'The END'
  text: '本文已结束，感谢阅读!'

# 数学公式
mathjax: false
  # enable: true
  # per_page: true

# Open link in a new tab | 是否在新窗口打开链接
open_in_new:
  article: true  # 文章链接
  menu: false   # 导航菜单
  subNav: false  # 子菜单

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: 'Thinks for your support!'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /img/alipay.jpg
# 微信二维码图片地址
weixin: /img/wechat.png

# 目录 如果某个文章不需要目录,可以指定文章layout: post-noTOC实现
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

#是否开启分享
socialShare: true
#是否开启云标签
# tagcloud: true
# hexo-tag-cloud 
tagcloud:
  enable: true
  textFont: 'Trebuchet MS, Helvetica'
  textColor: '#42a5f5'
  textHeight: 15
  outlineColor: '#fc9867'
  maxSpeed: 0.3 # range from [0.01 ~ 1]

#是否开启捐赠
donate: true
#是否开启站内搜索
search: true

#是否开启最近通知
recent: true
recentContent: ''
#是否开启微简历
resume: true

# Miscellaneous
# 百度统计
baidu_analytics: ''
google_analytics: ''

# 网站图标
favicon: /images/site-icon/svg/MrYao02.svg

# 你的头像url
avatar: /images/avatar.jpg  

# 是否开启分享
share_jia: true

# 评论： 1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment；6、Giteement ;7、gitalk ;8、valine ;9、utteranc评论
# 具体请参考wiki：https://github.com/JoeyBling/hexo-theme-yilia-plus/wiki
# 是否开启评论, 不需要使用某项，直接设置值为false，或注释掉

# 1、多说
duoshuo: false

# 2、网易云跟帖
wangyiyun: false

# 3、畅言
changyan_appid: false
changyan_conf: false

# 4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia-plus的
disqus: false

# 5、Gitment----基于GitHub的评论系统(关闭请设置gitment_owner为false)
# 关于如何集成:https://www.jianshu.com/p/ac7658cc912f
gitment_owner: false      # 你的 GitHub ID  e.g. YaoJusheng
# 是否使用官方js(false可以提升访问速度，本地修改过一部分的js，官方js可能会出现服务器不稳定，不太建议使用)
gitment_repo: 'YaoJusheng.github.io'          #存储评论的 repo name(需要在Github创建)
gitment_oauth:
  client_id: '35890ce192840bd76bc6'           #client ID
  client_secret: '18b465f1ea803824fe0aef032d74ce6262df3b6e'       #client secret

# 6、Giteement----【国内用户建议使用这个，相对比较快】
# 关于如何集成:https://www.jianshu.com/p/f5c4633524c7
# 基于码云的评论系统(https://gitee.com/zhousiwei/giteement)
giteement:
  enable: false  # 是否启用码云评论系统
  # 是否使用官方js(false可以提升访问速度)
  remote: false
  redirect_uri: https://yaojusheng.gitee.io/blog/   # 应用回调地址(请和配置的第三方应用保持一致)
  # 不能更改(网上开源项目`https://github.com/Rob--W/cors-anywhere`作者提供的专门用来跨域服务器的配置)
  oauth_uri: https://cors-anywhere.herokuapp.com/https://gitee.com/oauth/token
  giteeID: yaojusheng  # 你的码云账号英文名
  # 存储评论的 repo name(需要在码云仓库创建公开仓库)
  repo: blog
  gitment_oauth:
    client_id: '08574314fd7e0914b566851ee1949fa8e0e7b6538f9b6e2cb742103f6a26cfc9'           #client ID
    client_secret: '7a058b4578762f4002ab6686e600693619778f435bff63a92325f846741290e3'       #client secret

# 7、gitalk评论
gitalk:
  enable:  false
  githubID:  YaoJusheng   
  repo:  'yaojusheng.gitee.io'
  ClientID:  '35890ce192840bd76bc6'
  ClientSecret:  '18b465f1ea803824fe0aef032d74ce6262df3b6e'
  adminUser:  YaoJusheng
  distractionFreeMode: true

# 8、valine 评论系统，到leancloud进行注册
# https://leancloud.cn/dashboard/login.html#/signup
valine: 
 appid: 'oT30CtobWiSnNhMrBtXP9d0A-gzGzoHsz'  # Leancloud应用的appId
 appkey: 'oVHGMlRjJJyTXPLmyrGKrWFu'          # Leancloud应用的appKey
 verify: false      # 验证码
 notify: true       # 评论回复提醒
 avatar: wavatar        # 评论列表头像样式（https://valine.js.org/avatar）mm
 placeholder: 有话要说？ # 评论框占位符

# 9、utteranc评论： https://utteranc.es (参数配置详见主页) 替换 gitment、gitalk
utterance:
  enable: true
  repo: 'yaojusheng/yaojusheng.github.io'     #仓库名字,格式：你的用户ID/仓库名称，如：blog/utterance_repo
  issue_term: 'title'            #映射配置
  theme: 'github-light'          #主题

# Daovoice DaoCloud 在线沟通
daovoice: true 
daovoice_app_id: "6d0092ef"   # 6d0092ef/ eb35ef31

# 访问量统计功能(不蒜子)
busuanzi:
  enable: true
  site_visit: true  # 站点访问量显示
  article_visit: true  # 文章访问量显示

# 网易云音乐插件
music:
  enable: true
  # 播放器尺寸类型(1：短尺寸、2：长尺寸)
  type: 2
  id: 27580009  # 网易云分享的音乐ID(更换音乐请更改此配置项)
  autoPlay: true  # 是否开启自动播放
  # 提示文本(关闭请设置为false)
  text: '悠扬的旋律，为谁而敲响！'

# 页面点击小红心
clickLove:
  # (关闭请设置为false)
  enable: true

# fork 项目 GitHub Ribbons(https://github.blog/2008-12-19-github-ribbons/)
github: false
  # (关闭请设置为false)
  # url: https://github.com/JoeyBling/hexo-theme-yilia-plus

# Progress Bar | 页面加载进度条
# Demo: http://github.hubspot.com/pace/docs/welcome/
# type: barber-shop|big-counter|bounce|center-atom|center-circle|
#       center-radar|center-simple|corner-indicator|flash|flat-top|
#       loading-bar|mac-osx|minimal
# color: black|blue|green|orange|pink|purple|red|silver|white|yellow|
progressBar:
  enable: true
  type: 'minimal'  # Keep Quotes | 保留引号避免出错(某些type会导致样式重叠排版错误)
  color: blue

# Apple Touch icon 苹果图标(关闭请设置为false)
apple_touch_icon: '/apple-touch-icon-180x180.png'

# Tab Title Change | 标签页标题切换
tab_title_change:
  enable: true
  left_tab_title: '(つェ⊂) 我藏好了哦~ '
  return_tab_title: '(*´∇｀*) 被你发现啦~ '

# https://github.com/willin/hexo-wordcount
# 是否开启字数统计(关闭请设置enable为false)
# 也可以单独在md文件里Front-matter设置`no_word_count: true`属性，来自定义关闭字数统计
word_count:
  enable: true
  # 只在文章详情显示(不在首页显示)
  only_article_visit: true

# 文字输入特效
# https://github.com/disjukr/activate-power-mode
activate_power_mode:
  enable: true
  # 使输入模式丰富多彩
  colorful: true
  # 是否开启摇动
  shake: false

# 心知天气
xinzhi_weather: true

# 飘雪特效1
# https://github.com/MlgmXyysd/snow.js
snow: true
# 雪花特效2
snow2: true
# 代码雨
code_rain: false

# https://github.com/hustcc/canvas-nest.js
# 配置详见： https://github.com/hustcc/canvas-nest.js#configuration
# 动态线条效果，会向鼠标集中
canvas_nest:
  enable: true
  color: '206, 187, 13'        # color of lines, default: '0,0,0'; RGB values: (R,G,B).(note: use ',' to separate.)
  pointColor: '249, 72, 137'     # color of points, default: '0,0,0'; RGB values: (R,G,B).(note: use ',' to separate.)
  opacity: '0.9'               # the opacity of line (0~1), default: 0.5.
  count: '256'                  # the number of lines, default: 99.
  zIndex: '-1'                 # z-index property of the background, default: -1. 底层

# 看板娘动态模型插件
## https://github.com/JoeyBling/live2d-widget.js
live2d:
  # (关闭请设置为false)
  enable: true
  # 模型名称(取值请参考：https://github.com/JoeyBling/hexo-theme-yilia-plus/wiki/live2d%E6%A8%A1%E5%9E%8B%E5%8C%85%E5%B1%95%E7%A4%BA)
  # hibiki|epsilon2_1|chitose|izumi|gf|haru/01|haru/02|miku|ni-j|nico|nietzsche|
  # nipsilon|nito|shizuku|tsumiki|wanko|z16|koharu|haruto|unitychan|tororo|hijiki
  model: koharu
  display:
    position: right # 显示位置：left/right(default: 'right')
    width: 145  # 模型的长度(default: 150)
    height: 315 # 模型的高度(default: 300)
    hOffset: 50 # 水平偏移(default: 0)
    #vOffset: -20 # 垂直偏移(default: -20)
  mobile:
    show: false # 是否在移动设备上显示(default: true)
    scale: 0.6 # 移动设备上的缩放(default: 0.5)
  react:
    opacity: 0.8 # 模型透明度(default: 0.7)

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色 e.g. linear-gradient(rgba(255, 255, 255, 0.5), rgba(255, 255, 255, 0.5))
  # header: '#D3D1DC'
  header: 'rgba(0,0,0,0.5)' #设置背景透明度，不然头像上方是默认色
  #左侧头像板块的背景颜色(IE兼容设置：filter:alpha(opacity=80);)
  left_ground: 
    enable: true
    default: 'rgba(0,0,0,0.5)'
    # url: 'url(http://q5ndkf89x.bkt.clouddn.com/images/background/36.jpg) no-repeat 100%;background-size:cover;opacity:0.8;filter:alpha(opacity=80);'
    url: 'url(http://q5ndkf89x.bkt.clouddn.com/images%2Fcode%2Fcode-15.jpg) no-repeat 100%;background-size:cover;opacity:0.8;filter:alpha(opacity=80);'
  # 左侧头像板块动态图效果
  gif:
    # 是否启用
    enable: true
    # 自定义背景图路径(默认可以不设置，提供默认背景图biubiubiu.gif)
    path: /img/back-02.gif
  # 正文的背景颜色(IE兼容设置：opacity:0.8;filter:alpha(opacity=80);)
  article_ground: 
    enable: true
    default: 'rgba(25, 25, 25, 0)'  #设置背景透明度
    # url: 'url(http://q5ndkf89x.bkt.clouddn.com/images/background/39.jpg) no-repeat 100%;background-size:cover;opacity:0.7;filter:alpha(opacity=70);'
    url: 'url(http://q5ndkf89x.bkt.clouddn.com//images/background/44.jpg) no-repeat 100%;background-size:cover;opacity:0.7;filter:alpha(opacity=70);'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#ccc,#000)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 友情链接
friends:
  Google搜索: 
    url: https://www.google.com/
    ico: /images/ico/google_favicon.ico
    description: 最受欢迎的搜索引擎，国内使用可用代理或安装助手
  Bing搜索: 
    url: https://cn.bing.com/
    ico: /images/ico/biying_favicon.ico
    description: 必应搜索，一款好用的搜索引擎
  Translate: 
    url: https://translate.google.cn/
    ico: /images/ico/fanyi_favicon.ico
    description: 谷歌翻译
  bilibili: 
    url: https://www.bilibili.com/
    ico: /images/ico/bili_favicon.ico
    description: 技术视频网站
  知乎: 
    url: https://www.zhihu.com/
    ico: /images/ico/zhihu_favicon.ico
    description: 知识、技术交流平台
  在线工具: 
    url: https://tool.lu/
    ico: /images/ico/onlinetool.ico
    description: 全面多样化的开发、站长类工具
  百度字体编辑器: 
    url: http://fontstore.baidu.com/static/editor/index.html
    ico: /images/ico/font_favicon.ico
    description: 可制作图形文字，减少字体体积
  绘图draw: 
    url: https://www.draw.io/
    ico: /images/ico/draw_favicon.ico
    description: 一款在线绘制流程图的网页工具
  百度脑图: 
    url: https://naotu.baidu.com/home
    ico: /images/ico/naotu_favicon.ico
    description: 一款可替代XMind的在线思维导图工具
  
  更多: '#'

# 代码高亮
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# 关于我
aboutme: <div style="text-align:center"><span style="color:yellow;font-size:20px;">主要涉及技术：</span><br><br><div style="color:lightblue;">Python开发<br>PHP、前端开发<br>Ruby开发、Linux<br><br>联系QQ:870560379<br><br>很惭愧...<br>只做了一点微小的工作<br>谢谢大家!</div></div>

# 页脚 Litten(此配置项已弃用)
# 帮助我们让更多人可以更方便使用Hexo，请尽量不要修改此主题配置
pageFooter:
  litten: GitHub:<a href="https://github.com/JoeyBling/hexo-theme-yilia-plus" target="_blank">hexo-theme-yilia-plus</a>

# 开启百度站长平台自动推送(https://ziyuan.baidu.com/linksubmit/index)
baidu_push: true

# 版权声明
# 版权声明type设定：0-关闭版权声明； 1-文章对应的md文件里有copyright: true属性，才有版权声明； 2-所有文章均有版权声明
copyright:
  copyright_type: 2
  licensee_url: https://creativecommons.org/licenses/by-nc-sa/4.0/        #当前应用的版权协议地址。
  licensee_name: 'CC BY-NC-SA 4.0'                                        #版权协议的名称
  licensee_alias: '知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议'       # alias别名
  # https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png
  licensee_img: /images/copyright.png    #版权协议的Logo (/images/copyright.png)
  # 版权声明自定义文本(关闭请设置为false)
  copyright_text: 

# 网站成立年份(默认为 2020，若填入年份小于当前年份，则显示为 2019-2020 类似的格式)
since: 2020